apiVersion: v1
kind: Service
metadata:
  name: sportsstore
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: sportsstore
  type: NodePort
