apiVersion: v1
kind: Secret
metadata:
  name: sportsstore-secret
  labels:
    name: sportsstore-secret
    app: sportsstore-gke-deployment
  namespace: development
type: Opaque
data:
  mysql-password: d2ludGVy
