apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    name: mysql-data-storea
    app: mysql-gke-deployment
  namespace: development
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS`sportsstore`;
    USE `sportsstore`;
    DROP TABLE IF EXISTS `product`;
    CREATE TABLE `product` (
      `price` int DEFAULT NULL,
      `product_id` bigint NOT NULL AUTO_INCREMENT,
      `category` varchar(255) DEFAULT NULL,
      `description` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`product_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    LOCK TABLES `product` WRITE;
    INSERT INTO `product` VALUES (49,2,'Watersports','Protective and fashionable','Lifejacket'),(20,3,'Soccer','FIFA-approved size and weight','Soccer Ball'),(35,4,'Soccer','Give your playing field a professional touch','Corner Flags'),(79500,5,'Soccer','Flat-packed 35,000-seat stadium','Stadium'),(16,6,'Chess','Improve brain efficiency by 75%','Thinking Cap'),(30,7,'Chess','Secretly give your opponent a disadvantage','Unsteady Chair'),(75,8,'Chess','A fun game for the family','Human Chess Board'),(1200,9,'Chess','Gold-plated, diamond-studded King','Bling King'),(10,11,'Living Room','Red Sofa','Sofa');
    UNLOCK TABLES;
    DROP TABLE IF EXISTS `orders`;
    CREATE TABLE `orders` (
      `shipped` bit(1) DEFAULT NULL,
      `order_id` bigint NOT NULL AUTO_INCREMENT,
      `address` varchar(255) DEFAULT NULL,
      `city` varchar(255) DEFAULT NULL,
      `country` varchar(255) DEFAULT NULL,
      `name` varchar(255) DEFAULT NULL,
      `state` varchar(255) DEFAULT NULL,
      `zip` varchar(255) DEFAULT NULL,
      `cart_id` bigint DEFAULT NULL,
      PRIMARY KEY (`order_id`),
      KEY `orders_cart_FK` (`cart_id`),
      CONSTRAINT `orders_cart_FK` FOREIGN KEY (`cart_id`) REFERENCES `cart` (`cart_id`) ON DELETE CASCADE ON UPDATE CASCADE
    ) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    LOCK TABLES `orders` WRITE;
    UNLOCK TABLES;
    DROP TABLE IF EXISTS `cart`;
    CREATE TABLE `cart` (
      `cart_price` bigint DEFAULT NULL,
      `cart_id` bigint NOT NULL AUTO_INCREMENT,
      `item_count` int DEFAULT NULL,
      PRIMARY KEY (`cart_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    LOCK TABLES `cart` WRITE;
    INSERT INTO `cart` VALUES (1550,27,2),(1550,28,2),(40,29,2),(35,30,1);
    UNLOCK TABLES;
    DROP TABLE IF EXISTS `cartline`;
    CREATE TABLE `cartline` (
      `cart_line_id` bigint NOT NULL AUTO_INCREMENT,
      `quantity` int DEFAULT NULL,
      `product_id` bigint DEFAULT NULL,
      `cart_id` bigint DEFAULT NULL,
      PRIMARY KEY (`cart_line_id`),
      KEY `CartLine_product_FK` (`product_id`),
      KEY `cartline_cart_FK` (`cart_id`),
      CONSTRAINT `cartline_cart_FK` FOREIGN KEY (`cart_id`) REFERENCES `cart` (`cart_id`) ON DELETE CASCADE ON UPDATE CASCADE,
      CONSTRAINT `CartLine_product_FK` FOREIGN KEY (`product_id`) REFERENCES `product` (`product_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    INSERT INTO `cartline` VALUES (23,3,2,27),(24,7,7,27),(25,3,2,28),(26,7,7,28),(27,1,4,30);
    UNLOCK TABLES;
